# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160507_0654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poem',
            new_name='Book',
        ),
    ]
