# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160507_0700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Poem',
        ),
    ]
