# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160507_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
    ]
