# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=1024, null=True)),
                ('title', models.CharField(max_length=1024)),
            ],
        ),
    ]
